#!/bin/sh

echo AWCONSOLE-env: 
read c
	
if [ $c -eq "OUTPUT" ] 
do
  sleep 1
  echo AWCONSOLE-env-:OUTPUT: 
  read print
  echo $print
  
fi

if [ $c -eq "EXECUTE" ] 
do
  read file
  while [ $c -eq "OUTPUT" ]
  do
     echo $a
     a=`expr $a + 1`
  done

fi
